services:
  database:
    image: postgres:16-alpine3.19
    ports:
      - '5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  frontend:
    build:
      context: ./apps/test.local
      dockerfile: ../.docker/Dockerfile
    ports:
      - '3001:80'
